[workspace]
resolver = "2"

members = ["day-*", "read_input"]
default-members = ["day-*", "read_input"]

[workspace.dependencies]
nom = "7.1.3"
itertools = "0.13.0"
regex = "1.11.1"
regex-split = "0.1.0"